/*
 * MyBusiness Local AI Agent
 *
 * Deterministic business-action layer for the local Qwen-powered assistant.
 *
 * IMPORTANT:
 * - This file does NOT change the Firebase/Firestore data model.
 * - It does NOT execute arbitrary JavaScript generated by Qwen.
 * - It only performs registered actions defined below.
 * - Business calculations are performed by JavaScript, not Qwen.
 * - Qwen can be used by the surrounding AI layer for language understanding,
 *   while this module remains the safety/execution layer.
 *
 * Public API:
 *   handleAgentCommand(input)
 *   agentContext()
 */

const WORDS = {
  receiveCustomer: [
    'receive','received','receiving','collect','collected','got','get',
    'wapas','wapis','wasool','wasol','vasol','liya','le liya','le lia',
    'mil gaya','mil gaye','mila','mile','aa gaya','aa gaye',
    'paisay mil gaye','paise mil gaye',
    'وصول','وصولی','لیا','ملا','ملے','آ گئے'
  ],

  giveCustomer: [
    'give','gave','giving','credit','add debt','owe','owes',
    'udhaar','udhar','qarz','diya','de diya','de dia',
    'da do','dado','dade','dedo','de do',
    'دیا','ادھار','واجب','قرض'
  ],

  addStock: [
    'add','increase','increasing','put','restock','refill',
    'dal','daal','dal do','daal do','jama','jama karo',
    'barha do','barhao','barhado',
    'جمع','اضافہ','شامل','بڑھاؤ'
  ],

  removeStock: [
    'remove','decrease','decreasing','minus','reduce','reducing',
    'deduct','kam','kamm','nikal','nikal do','nikalo',
    'ghata do','ghatao','ghatado',
    'کم','منہا','نکال','گھٹاؤ'
  ],

  supplierPayment: [
    'pay','paid','paying','payment',
    'ada','ada kiya','ada kar diya',
    'ادا','ادائیگی'
  ],

  supplierDebt: [
    'credit','debt','owe','owes',
    'udhaar','udhar','qarz','purchase debt',
    'ادھار','واجب','قرض'
  ],

  expense: [
    'expense','expenses','spent','spend','cost',
    'kharcha','kharch','kharcha kiya','kharch kiya',
    'خرچہ','اخراجات','خرچ'
  ],

  addCustomer: [
    'add','create','new','banao','banayen',
    'بناؤ','بنائیں','شامل'
  ],

  addProduct: [
    'add','create','new','banao','banayen',
    'بناؤ','بنائیں','شامل'
  ],

  sellProduct: [
    'sale karo','sell karo','sale kr do','sale kro',
    'sale kar do','becho','bech do','farokht karo',
    'sell it','make a sale',
    'فروخت کرو','بیچو','بیچ دو'
  ]
};


/* -------------------------------------------------------------------------- */
/* NORMALIZATION                                                              */
/* -------------------------------------------------------------------------- */

const norm = value =>
  String(value || '')
    .toLowerCase()
    .normalize('NFKC')
    .replace(/[؟?!.،,؛;:]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

const money = value =>
  window.formatCurrency
    ? window.formatCurrency(Number(value) || 0)
    : `Rs. ${(Number(value) || 0).toLocaleString()}`;

const ownerId = () =>
  window.currentUserId ||
  window.authUserId ||
  null;

function requireUser() {
  if (!ownerId()) {
    throw new Error('Please log in again before using the AI agent.');
  }
}


/* -------------------------------------------------------------------------- */
/* NUMBER PARSING                                                             */
/* -------------------------------------------------------------------------- */

const UNIT_WORDS = {
  ek: 1,
  aik: 1,
  one: 1,

  do: 2,
  two: 2,

  teen: 3,
  three: 3,

  char: 4,
  chaar: 4,
  four: 4,

  panch: 5,
  paanch: 5,
  five: 5,

  chay: 6,
  che: 6,
  chhay: 6,
  six: 6,

  saat: 7,
  seven: 7,

  aath: 8,
  eight: 8,

  nau: 9,
  nine: 9,

  das: 10,
  ten: 10,

  gyara: 11,
  gyarah: 11,

  barah: 12,

  pandra: 15,
  pandrah: 15,

  bees: 20,
  pachas: 50,
  sattar: 70,
  assi: 80,
  nabbe: 90
};

function numberFrom(value) {
  const text = String(value || '').replace(/,/g, '');

  const match = text.match(
    /(?:rs\.?|rs|rupees?|₨)?\s*(-?\d+(?:\.\d+)?)/i
  );

  return match ? Number(match[1]) : NaN;
}

function numberFromWords(value) {
  const text = norm(value);

  if (!text) return NaN;

  const direct = UNIT_WORDS[text];
  if (Number.isFinite(direct)) return direct;

  let total = 0;
  let matched = false;

  const thousand = text.match(
    /(\w+)?\s*(?:hazar|hazaar|thousand)/
  );

  if (thousand) {
    const raw = thousand[1];
    const n = raw
      ? (UNIT_WORDS[raw] ?? numberFrom(raw))
      : 1;

    if (Number.isFinite(n)) {
      total += n * 1000;
      matched = true;
    }
  }

  const hundred = text.match(
    /(\w+)?\s*(?:sau|hundred)/
  );

  if (hundred) {
    const raw = hundred[1];
    const n = raw
      ? (UNIT_WORDS[raw] ?? numberFrom(raw))
      : 1;

    if (Number.isFinite(n)) {
      total += n * 100;
      matched = true;
    }
  }

  /*
   * Simple additive Roman-Urdu numbers:
   * "do sau pachas" -> 250
   * "ek hazar do sau" -> 1200
   */
  if (!matched) {
    const parts = text.split(/\s+/);

    let smallTotal = 0;

    for (const part of parts) {
      if (Number.isFinite(UNIT_WORDS[part])) {
        smallTotal += UNIT_WORDS[part];
        matched = true;
      }
    }

    if (matched) total = smallTotal;
  }

  return matched ? total : NaN;
}

function amountFrom(value) {
  const numeric = numberFrom(value);

  if (Number.isFinite(numeric)) {
    return numeric;
  }

  return numberFromWords(value);
}

function qtyFrom(value) {
  const text = norm(value);

  /*
   * Prefer numbers immediately associated with quantity language.
   */
  const explicit = text.match(
    /(\d+(?:\.\d+)?)\s*(?:x|pcs?|pieces?|piece|units?|unit|items?|item|qty|quantity|پیس|عدد)\b/i
  );

  if (explicit) {
    return Math.max(1, Math.floor(Number(explicit[1])));
  }

  /*
   * Common:
   * "10 Pepsi add"
   * "Pepsi 10 add"
   */
  const digits = text.match(/\b(\d+(?:\.\d+)?)\b/);

  if (digits) {
    return Math.max(1, Math.floor(Number(digits[1])));
  }

  return 1;
}


/* -------------------------------------------------------------------------- */
/* REGEX HELPERS                                                              */
/* -------------------------------------------------------------------------- */

function escapeRegex(value) {
  return String(value || '')
    .replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function rx(words) {
  return new RegExp(
    '(?:' +
      words
        .map(word =>
          escapeRegex(word).replace(/\s+/g, '\\s*')
        )
        .join('|') +
    ')',
    'i'
  );
}

const RX = {
  stock: /(?:stock|inventory|stok|سٹاک|اسٹاک|ذخیرہ)/i,

  quantity: /(?:pcs?|pieces?|piece|units?|unit|items?|item|qty|quantity|پیس|عدد)/i,

  customer: /(?:customer|client|grahak|gاہک|گاہک)/i,

  supplier: /(?:supplier|vendor|سپلائر|فراہم کنندہ)/i,

  balance: /(?:balance|due|debt|owe|owes|udhaar|udhar|qarz|kitna|kitne|how much|واجب|ادھار|قرض|کتنا|کتنے)/i,

  sale: /(?:sale|sales|sold|sell|فروخت|فروختیں|سیل)/i,

  profit: /(?:profit|munafa|munafa|منافع|منافعہ)/i,

  expense: /(?:expense|expenses|kharcha|kharch|خرچہ|اخراجات|خرچ)/i,

  today: /(?:today|aaj|آج)/i,

  yesterday: /(?:yesterday|kal|گزشتہ کل|کل)/i,

  tomorrow: /(?:tomorrow|kal|کل)/i,

  lowStock: /(?:low stock|low inventory|kam stock|کم اسٹاک|کم سٹاک)/i,

  productsList: /(?:all products|product list|products list|show products|تمام پروڈکٹس|پروڈکٹس دکھاؤ)/i,

  confirm: /^(?:yes|y|haan|han|جی|ہاں|ok|okay|confirm|confirmed|kar do|kardo|do it|جی ہاں)$/i,

  cancel: /^(?:no|n|nah|nahi|نہیں|cancel|cancel it|mat karo|rehne do|رہنے دو)$/i
};


/* -------------------------------------------------------------------------- */
/* FUZZY MATCHING                                                             */
/* -------------------------------------------------------------------------- */

function levenshtein(a, b) {
  const left = String(a || '');
  const right = String(b || '');

  const dp = Array.from(
    { length: left.length + 1 },
    () => new Array(right.length + 1).fill(0)
  );

  for (let i = 0; i <= left.length; i++) {
    dp[i][0] = i;
  }

  for (let j = 0; j <= right.length; j++) {
    dp[0][j] = j;
  }

  for (let i = 1; i <= left.length; i++) {
    for (let j = 1; j <= right.length; j++) {
      dp[i][j] =
        left[i - 1] === right[j - 1]
          ? dp[i - 1][j - 1]
          : 1 +
            Math.min(
              dp[i - 1][j - 1],
              dp[i - 1][j],
              dp[i][j - 1]
            );
    }
  }

  return dp[left.length][right.length];
}


/*
 * Return all strong matches instead of silently choosing one.
 *
 * This is important for:
 *   Pepsi
 *   Pepsi 1.5L
 *   Pepsi 2.25L
 *
 * If more than one product/customer has the same usable match,
 * the agent asks instead of guessing.
 */
function findMentionedAll(list, sentence) {
  const text = norm(sentence);

  if (!Array.isArray(list) || !list.length) {
    return [];
  }

  const exact = list.filter(item => {
    if (!item?.name) return false;

    const name = norm(item.name);

    return (
      text === name ||
      text.includes(` ${name} `) ||
      text.startsWith(`${name} `) ||
      text.endsWith(` ${name}`)
    );
  });

  if (exact.length) {
    return exact;
  }

  const words = text.split(/\s+/).filter(Boolean);

  const candidates = [];

  for (const item of list) {
    if (!item?.name) continue;

    const name = norm(item.name);
    const nameWords = name.split(/\s+/).length;

    for (let i = 0; i < words.length; i++) {
      const window = words
        .slice(i, i + nameWords)
        .join(' ');

      if (!window) continue;

      const distance = levenshtein(window, name);

      const limit = Math.max(
        1,
        Math.floor(name.length * 0.25)
      );

      if (distance <= limit) {
        candidates.push({
          item,
          distance
        });
      }
    }
  }

  candidates.sort((a, b) => a.distance - b.distance);

  if (!candidates.length) return [];

  const bestDistance = candidates[0].distance;

  return candidates
    .filter(x => x.distance === bestDistance)
    .map(x => x.item);
}

function resolveEntity(list, sentence, label) {
  const matches = findMentionedAll(list, sentence);

  if (!matches.length) {
    return {
      found: false,
      ambiguous: false,
      item: null,
      matches: []
    };
  }

  if (matches.length === 1) {
    return {
      found: true,
      ambiguous: false,
      item: matches[0],
      matches
    };
  }

  return {
    found: true,
    ambiguous: true,
    item: null,
    matches,
    question:
      `I found more than one ${label} matching that name: ` +
      matches
        .slice(0, 8)
        .map(x => x.name)
        .join(', ') +
      '. Which one do you mean?'
  };
}

function names(list, max = 30) {
  return list
    .slice(0, max)
    .map(x => x?.name)
    .filter(Boolean)
    .join(', ');
}


/* -------------------------------------------------------------------------- */
/* SHORT-TERM CONVERSATION CONTEXT                                            */
/* -------------------------------------------------------------------------- */

const CONTEXT_KEY = '__myBusinessAiContext';

function getContext() {
  if (!window[CONTEXT_KEY]) {
    window[CONTEXT_KEY] = {
      product: null,
      customer: null,
      supplier: null,
      lastAction: null,
      lastText: '',
      timestamp: 0
    };
  }

  return window[CONTEXT_KEY];
}

function clearOldContext() {
  const context = getContext();

  /*
   * Do not keep unrelated entities forever.
   * Five minutes is enough for normal follow-up commands.
   */
  if (
    context.timestamp &&
    Date.now() - context.timestamp > 5 * 60 * 1000
  ) {
    context.product = null;
    context.customer = null;
    context.supplier = null;
    context.lastAction = null;
    context.lastText = '';
  }
}

function rememberContext({
  product = undefined,
  customer = undefined,
  supplier = undefined,
  action = undefined,
  text = undefined
}) {
  const context = getContext();

  if (product !== undefined) context.product = product;
  if (customer !== undefined) context.customer = customer;
  if (supplier !== undefined) context.supplier = supplier;
  if (action !== undefined) context.lastAction = action;
  if (text !== undefined) context.lastText = text;

  context.timestamp = Date.now();
}

function contextProduct() {
  clearOldContext();
  return getContext().product || null;
}

function contextCustomer() {
  clearOldContext();
  return getContext().customer || null;
}

function contextSupplier() {
  clearOldContext();
  return getContext().supplier || null;
}


/* -------------------------------------------------------------------------- */
/* CONFIRMATION                                                               */
/* -------------------------------------------------------------------------- */

function confirmationText(action) {
  window.__myBusinessAiPending = action;

  rememberContext({
    product: action.product ?? undefined,
    customer: action.customer ?? undefined,
    supplier: action.supplier ?? undefined,
    action
  });

  return (
    `${action.summary}\n\n` +
    'Confirm this task by choosing Yes or No.'
  );
}

function isYes(value) {
  return RX.confirm.test(norm(value));
}

function isNo(value) {
  return RX.cancel.test(norm(value));
}


/* -------------------------------------------------------------------------- */
/* DATE HELPERS                                                               */
/* -------------------------------------------------------------------------- */

function localDate(value = new Date()) {
  if (window.getLocalDateStr) {
    return window.getLocalDateStr(
      value instanceof Date ? value : new Date(value)
    );
  }

  const d = value instanceof Date ? value : new Date(value);

  if (Number.isNaN(d.getTime())) return '';

  return [
    d.getFullYear(),
    String(d.getMonth() + 1).padStart(2, '0'),
    String(d.getDate()).padStart(2, '0')
  ].join('-');
}

function dateMatches(value, target) {
  return localDate(value) === target;
}

function todayDate() {
  return localDate(new Date());
}

function yesterdayDate() {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return localDate(d);
}


/* -------------------------------------------------------------------------- */
/* SAFE DATA ACCESS                                                           */
/* -------------------------------------------------------------------------- */

function dataSet(name) {
  const data = window.data || {};
  return Array.isArray(data[name]) ? data[name] : [];
}

function products() {
  return dataSet('products');
}

function customers() {
  return dataSet('customers');
}

function suppliers() {
  return dataSet('suppliers');
}

function sales() {
  return dataSet('sales');
}

function expenses() {
  return dataSet('expenses');
}


/* -------------------------------------------------------------------------- */
/* ACTION REGISTRY                                                            */
/* -------------------------------------------------------------------------- */

const ACTIONS = Object.freeze({

  addStock: {
    purpose: 'Increase product stock',
    required: ['product', 'qty'],
    confirmation: true
  },

  removeStock: {
    purpose: 'Decrease product stock',
    required: ['product', 'qty'],
    confirmation: true
  },

  receiveCustomer: {
    purpose: 'Receive payment from customer',
    required: ['customer', 'amount'],
    confirmation: true
  },

  giveCustomer: {
    purpose: 'Add customer credit/debt',
    required: ['customer', 'amount'],
    confirmation: true
  },

  addCustomer: {
    purpose: 'Create customer',
    required: ['name'],
    confirmation: true
  },

  addProduct: {
    purpose: 'Create product',
    required: ['name'],
    confirmation: true
  },

  supplierPayment: {
    purpose: 'Pay supplier',
    required: ['supplier', 'amount'],
    confirmation: true
  },

  supplierDebt: {
    purpose: 'Add supplier payable',
    required: ['supplier', 'amount'],
    confirmation: true
  },

  expense: {
    purpose: 'Record expense',
    required: ['amount'],
    confirmation: true
  },

  sellProduct: {
    purpose: 'Sell product',
    required: ['product', 'qty'],
    confirmation: true
  },

  sellProducts: {
    purpose: 'Sell one or more products in one sale',
    required: ['items'],
    confirmation: true
  }

});


function isRegisteredAction(type) {
  return Boolean(
    type &&
    Object.prototype.hasOwnProperty.call(ACTIONS, type)
  );
}


/* -------------------------------------------------------------------------- */
/* VALIDATION                                                                 */
/* -------------------------------------------------------------------------- */

function validateAction(action) {
  if (!action || !isRegisteredAction(action.type)) {
    return {
      valid: false,
      error: 'Unsupported agent action.'
    };
  }

  if (action.product && !action.product.id) {
    return {
      valid: false,
      error: 'The selected product is missing its ID.'
    };
  }

  if (action.customer && !action.customer.id) {
    return {
      valid: false,
      error: 'The selected customer is missing its ID.'
    };
  }

  if (action.supplier && !action.supplier.id) {
    return {
      valid: false,
      error: 'The selected supplier is missing its ID.'
    };
  }

  if (
    ['addStock', 'removeStock', 'sellProduct'].includes(action.type)
  ) {
    if (
      !Number.isFinite(Number(action.qty)) ||
      Number(action.qty) <= 0
    ) {
      return {
        valid: false,
        error: 'Quantity must be greater than zero.'
      };
    }
  }

  if (action.type === 'sellProducts') {
    if (!Array.isArray(action.items) || !action.items.length) {
      return { valid: false, error: 'At least one product is required for a sale.' };
    }
    for (const item of action.items) {
      if (!item?.product?.id || !Number.isFinite(Number(item.qty)) || Number(item.qty) <= 0) {
        return { valid: false, error: 'Each sale item must have a valid product and quantity.' };
      }
    }
  }

  if (
    [
      'receiveCustomer',
      'giveCustomer',
      'supplierPayment',
      'supplierDebt',
      'expense'
    ].includes(action.type)
  ) {
    if (
      !Number.isFinite(Number(action.amount)) ||
      Number(action.amount) <= 0
    ) {
      return {
        valid: false,
        error: 'Amount must be greater than zero.'
      };
    }
  }

  return { valid: true };
}


/* -------------------------------------------------------------------------- */
/* EXECUTION                                                                  */
/* -------------------------------------------------------------------------- */

async function execute(action) {
  requireUser();

  const validation = validateAction(action);

  if (!validation.valid) {
    throw new Error(validation.error);
  }

  if (!isRegisteredAction(action.type)) {
    throw new Error('Unsupported agent action.');
  }

  const db = window.db;
  const doc = window.doc;
  const collection = window.collection;

  if (!db || !doc || !collection) {
    throw new Error(
      'The database interface is not available.'
    );
  }

  /*
   * ------------------------------------------------------------------------
   * STOCK
   * ------------------------------------------------------------------------
   */

  if (
    action.type === 'addStock' ||
    action.type === 'removeStock'
  ) {
    const ref = doc(
      db,
      'products',
      action.product.id
    );

    let newStock = 0;

    await window.runAtomicOrOffline(async tx => {
      const snap = await tx.get(ref);

      if (!snap.exists()) {
        throw new Error('Product no longer exists.');
      }

      const data = snap.data();

      if (data.ownerId !== ownerId()) {
        throw new Error('Unauthorized product.');
      }

      const current = Number(data.stock) || 0;

      /*
       * MyBusiness supports negative stock.
       * Do not clamp it to zero.
       */
      newStock =
        action.type === 'addStock'
          ? current + Number(action.qty)
          : current - Number(action.qty);

      tx.update(ref, {
        stock: newStock,
        updatedAt: new Date().toISOString()
      });

      const adjustmentRef = doc(
        collection(db, 'stockAdjustments')
      );

      tx.set(adjustmentRef, {
        ownerId: ownerId(),
        productId: action.product.id,
        type:
          action.type === 'addStock'
            ? 'add'
            : 'remove',
        quantity: Number(action.qty),
        date: new Date().toISOString(),
        note: 'AI agent'
      });
    });

    rememberContext({
      product: action.product,
      action
    });

    return (
      `Done. ${action.product.name} stock ` +
      `${action.type === 'addStock' ? 'increased' : 'decreased'} ` +
      `by ${action.qty}. New stock: ${newStock}.`
    );
  }


  /*
   * ------------------------------------------------------------------------
   * CUSTOMER PAYMENT / CREDIT
   * ------------------------------------------------------------------------
   */

  if (
    action.type === 'receiveCustomer' ||
    action.type === 'giveCustomer'
  ) {
    const ref = doc(
      db,
      'customers',
      action.customer.id
    );

    const transactionRef = doc(
      collection(db, 'customerTransactions')
    );

    let newBalance = 0;

    await window.runAtomicOrOffline(async tx => {
      const snap = await tx.get(ref);

      if (!snap.exists()) {
        throw new Error(
          'Customer no longer exists.'
        );
      }

      const data = snap.data();

      if (data.ownerId !== ownerId()) {
        throw new Error(
          'Unauthorized customer.'
        );
      }

      const current =
        Math.max(0, Number(data.balance) || 0);

      if (
        action.type === 'receiveCustomer' &&
        Number(action.amount) > current
      ) {
        throw new Error(
          `Amount exceeds customer due of ${money(current)}.`
        );
      }

      newBalance =
        action.type === 'receiveCustomer'
          ? Math.max(
              0,
              current - Number(action.amount)
            )
          : current + Number(action.amount);

      tx.update(ref, {
        balance: newBalance,
        updatedAt: new Date().toISOString()
      });

      tx.set(transactionRef, {
        ownerId: ownerId(),
        customerId: action.customer.id,

        type:
          action.type === 'receiveCustomer'
            ? 'payment'
            : 'manual_debt',

        amount: Number(action.amount),

        amountPaid:
          action.type === 'receiveCustomer'
            ? Number(action.amount)
            : 0,

        debitAmount:
          action.type === 'receiveCustomer'
            ? 0
            : Number(action.amount),

        creditAmount:
          action.type === 'receiveCustomer'
            ? Number(action.amount)
            : 0,

        balanceAfter: newBalance,

        date: new Date().toISOString(),

        note: 'AI agent',

        createdBy:
          window.authUserId ||
          window.currentUserId
      });
    });

    rememberContext({
      customer: action.customer,
      action
    });

    return (
      `Done. ${money(action.amount)} ` +
      `${
        action.type === 'receiveCustomer'
          ? 'received from'
          : 'added to'
      } ${action.customer.name}. ` +
      `New due: ${money(newBalance)}.`
    );
  }


  /*
   * ------------------------------------------------------------------------
   * CUSTOMER CREATION
   * ------------------------------------------------------------------------
   */

  if (action.type === 'addCustomer') {
    const existing = customers().filter(
      customer =>
        norm(customer.name) ===
        norm(action.name)
    );

    if (existing.length) {
      return (
        `Customer "${action.name}" already exists. ` +
        'No duplicate customer was created.'
      );
    }

    await window.addDoc(
      collection(db, 'customers'),
      {
        name: action.name,
        phone: action.phone || '',
        address: action.address || '',
        notes: action.notes || '',
        dueDate: null,
        balance: 0,
        createdAt: new Date().toISOString(),
        ownerId: ownerId()
      }
    );

    rememberContext({
      customer: {
        name: action.name
      },
      action
    });

    return (
      `Done. Customer "${action.name}" added successfully.`
    );
  }


  /*
   * ------------------------------------------------------------------------
   * PRODUCT CREATION
   * ------------------------------------------------------------------------
   */

  if (action.type === 'addProduct') {
    const existing = products().filter(
      product =>
        norm(product.name) ===
        norm(action.name)
    );

    if (existing.length) {
      return (
        `Product "${action.name}" already exists. ` +
        'No duplicate product was created.'
      );
    }

    const cost = Number(action.cost) || 0;
    const wholesalePrice =
      Number(action.wholesalePrice) || 0;
    const retailPrice =
      Number(action.retailPrice) || wholesalePrice;

    await window.addDoc(
      collection(db, 'products'),
      {
        name: action.name,
        barcode: action.barcode || '',
        cost,
        price: wholesalePrice,
        wholesalePrice,
        retailPrice,
        minStock:
          Number(action.minStock) || 5,
        stock:
          Number(action.stock) || 0,
        ownerId: ownerId()
      }
    );

    return (
      `Done. Product "${action.name}" added ` +
      `with stock ${Number(action.stock) || 0}.`
    );
  }


  /*
   * ------------------------------------------------------------------------
   * SUPPLIER
   * ------------------------------------------------------------------------
   */

  if (
    action.type === 'supplierPayment' ||
    action.type === 'supplierDebt'
  ) {
    const ref = doc(
      db,
      'suppliers',
      action.supplier.id
    );

    const transactionRef = doc(
      collection(db, 'supplierTransactions')
    );

    let newBalance = 0;

    await window.runAtomicOrOffline(async tx => {
      const snap = await tx.get(ref);

      if (!snap.exists()) {
        throw new Error(
          'Supplier no longer exists.'
        );
      }

      const data = snap.data();

      if (data.ownerId !== ownerId()) {
        throw new Error(
          'Unauthorized supplier.'
        );
      }

      const current =
        Math.max(0, Number(data.balance) || 0);

      if (
        action.type === 'supplierPayment' &&
        Number(action.amount) > current
      ) {
        throw new Error(
          `Payment exceeds supplier payable of ${money(current)}.`
        );
      }

      newBalance =
        action.type === 'supplierPayment'
          ? Math.max(
              0,
              current - Number(action.amount)
            )
          : current + Number(action.amount);

      tx.update(ref, {
        balance: newBalance
      });

      tx.set(transactionRef, {
        ownerId: ownerId(),
        supplierId: action.supplier.id,

        type:
          action.type === 'supplierPayment'
            ? 'payment'
            : 'manual_debt',

        amount: Number(action.amount),

        balanceAfter: newBalance,

        date: new Date().toISOString(),

        note: 'AI agent'
      });
    });

    rememberContext({
      supplier: action.supplier,
      action
    });

    return (
      `Done. ${money(action.amount)} ` +
      `${
        action.type === 'supplierPayment'
          ? 'paid to'
          : 'added as payable to'
      } ${action.supplier.name}. ` +
      `New payable: ${money(newBalance)}.`
    );
  }


  /*
   * ------------------------------------------------------------------------
   * EXPENSE
   * ------------------------------------------------------------------------
   */

  if (action.type === 'expense') {
    await window.addDoc(
      collection(db, 'expenses'),
      {
        amount: Number(action.amount),
        date: new Date().toISOString(),
        category:
          action.category || 'AI expense',
        note:
          action.note ||
          'Added by AI agent',
        ownerId: ownerId()
      }
    );

    return (
      `Done. Expense of ${money(action.amount)} recorded` +
      (
        action.category
          ? ` under ${action.category}.`
          : '.'
      )
    );
  }


  /*
   * ------------------------------------------------------------------------
   * SALE (single or multiple products)
   * ------------------------------------------------------------------------
   *
   * Retail is cash/paid sale in this agent path: it never creates customer
   * debt. If the user does not specify a payment amount, the full calculated
   * retail total is treated as paid. Wholesale keeps the existing customer-
   * debt behavior when a customer is explicitly selected.
   */

  if (action.type === 'sellProduct' || action.type === 'sellProducts') {
    const items = action.type === 'sellProduct'
      ? [{ product: action.product, qty: Number(action.qty) }]
      : action.items.map(item => ({ product: item.product, qty: Number(item.qty) }));

    const saleType = action.saleType === 'retail' ? 'retail' : 'wholesale';
    const customer = action.customer || null;
    const customerRef = saleType === 'wholesale' && customer
      ? doc(db, 'customers', customer.id)
      : null;
    const productRefs = items.map(item => doc(db, 'products', item.product.id));
    const billNumber = Math.max(
      0,
      ...sales().map(x => parseInt(x.invoiceNumber, 10)).filter(Number.isFinite)
    ) + 1;
    const saleRef = doc(collection(db, 'sales'));
    let resultText = '';

    await window.runAtomicOrOffline(async tx => {
      const refs = customerRef ? [...productRefs, customerRef] : productRefs;
      const snaps = await Promise.all(refs.map(ref => tx.get(ref)));
      const productSnapshots = items.map((item, index) => ({ item, snap: snaps[index] }));
      const customerSnap = customerRef ? snaps.at(-1) : null;

      let subtotal = 0;
      let totalProfit = 0;
      const saleItems = [];

      for (const { item, snap } of productSnapshots) {
        if (!snap.exists()) throw new Error(`Product ${item.product.name} no longer exists.`);
        const product = snap.data();
        if (product.ownerId !== ownerId()) throw new Error(`Unauthorized product: ${item.product.name}.`);

        const qty = Number(item.qty);
        const stock = Number(product.stock) || 0;
        if (qty > stock) {
          throw new Error(`Not enough stock for ${item.product.name}. Available: ${stock}.`);
        }

        const unit = saleType === 'retail'
          ? Number(product.retailPrice ?? product.price ?? 0)
          : Number(product.wholesalePrice ?? product.price ?? 0);
        const cost = Number(product.cost) || 0;
        const lineTotal = unit * qty;

        subtotal += lineTotal;
        totalProfit += (unit - cost) * qty;
        saleItems.push({
          id: item.product.id,
          name: product.name || item.product.name,
          price: unit,
          cost,
          qty,
          returnedQty: 0
        });

        tx.update(doc(db, 'products', item.product.id), {
          stock: stock - qty,
          updatedAt: new Date().toISOString()
        });
      }

      let amountPaid = saleType === 'retail'
        ? subtotal
        : Number(action.amountPaid || 0);
      if (amountPaid < 0) throw new Error('Amount paid cannot be negative.');
      if (saleType === 'retail') amountPaid = subtotal;
      const discount = Math.max(0, Math.min(subtotal, Number(action.discount || 0)));
      const total = Math.max(0, subtotal - discount);
      if (saleType === 'retail') amountPaid = total;
      const amountDue = saleType === 'retail' ? 0 : Math.max(0, total - amountPaid);
      const currentBalance = customerSnap?.exists()
        ? Math.max(0, Number(customerSnap.data().balance) || 0)
        : 0;
      const newCustomerBalance = currentBalance + amountDue;
      const customerName = customerSnap?.exists()
        ? customerSnap.data().name
        : (customer?.name || 'Walk-in');

      if (customerSnap?.exists() && customerSnap.data().ownerId !== ownerId()) {
        throw new Error('Unauthorized customer.');
      }

      tx.set(saleRef, {
        ownerId: ownerId(),
        createdBy: window.authUserId || window.currentUserId,
        createdByName: window.currentMemberName || 'Business Owner',
        customerId: customer ? customer.id : null,
        customerName,
        saleType,
        date: new Date().toISOString(),
        items: saleItems,
        subtotal,
        discount,
        discountType: 'amount',
        total,
        amountPaid,
        amountDue,
        totalProfit: totalProfit - discount,
        profitKnown: true,
        note: 'AI agent',
        returnedAmount: 0,
        returnedProfit: 0,
        invoiceNumber: billNumber
      });

      if (customerRef && amountDue > 0) {
        tx.update(customerRef, {
          balance: newCustomerBalance,
          updatedAt: new Date().toISOString()
        });
        const transactionRef = doc(collection(db, 'customerTransactions'));
        tx.set(transactionRef, {
          ownerId: ownerId(),
          customerId: customer.id,
          type: 'sale_debt',
          amount: amountDue,
          amountPaid,
          debitAmount: amountDue,
          creditAmount: amountPaid,
          balanceAfter: newCustomerBalance,
          date: new Date().toISOString(),
          note: `Bill No. ${billNumber}`,
          billNo: String(billNumber),
          saleId: saleRef.id,
          createdBy: window.authUserId || window.currentUserId
        });
      }

      tx.set(doc(db, 'settings', ownerId()), {
        nextInvoiceNumber: billNumber + 1
      }, { merge: true });

      resultText = saleType === 'retail'
        ? `Done. Retail sale recorded: ${saleItems.map(i => `${i.qty} x ${i.name}`).join(', ')} for ${money(total)}. No customer debt was created.`
        : `Done. Sale recorded: ${saleItems.map(i => `${i.qty} x ${i.name}`).join(', ')} for ${money(total)}${amountDue > 0 && customer ? `; ${money(amountDue)} added to ${customerName}'s due.` : '.'}`;
    });

    rememberContext({
      product: items.length === 1 ? items[0].product : undefined,
      customer: customer || undefined,
      action
    });

    return resultText;
  }

  throw new Error(
    'Unsupported agent action.'
  );
}


/* -------------------------------------------------------------------------- */
/* INFORMATION / REPORTS                                                      */
/* -------------------------------------------------------------------------- */

function parseInformationCommand(input) {
  const text = norm(input);

  const allProducts = products();
  const allCustomers = customers();
  const allSales = sales();

  /*
   * Specific product stock.
   */
  const productResult =
    resolveEntity(
      allProducts,
      text,
      'product'
    );

  if (
    productResult.ambiguous &&
    RX.stock.test(text)
  ) {
    return {
      kind: 'clarification',
      text: productResult.question
    };
  }

  if (
    productResult.found &&
    RX.stock.test(text) &&
    !rx(
      WORDS.addStock.concat(
        WORDS.removeStock
      )
    ).test(text)
  ) {
    rememberContext({
      product: productResult.item
    });

    return {
      kind: 'answer',
      text:
        `${productResult.item.name}: ` +
        `current stock ` +
        `${Number(productResult.item.stock) || 0}.`
    };
  }


  /*
   * Low stock.
   */
  if (RX.lowStock.test(text)) {
    const low =
      allProducts.filter(
        product =>
          Number(product.stock || 0) <=
          Number(product.minStock || 5)
      );

    return {
      kind: 'answer',
      text:
        low.length
          ? `Low stock: ${low
              .map(
                product =>
                  `${product.name} (${product.stock})`
              )
              .join(', ')}`
          : 'No low-stock products found.'
    };
  }


  /*
   * All products.
   */
  if (RX.productsList.test(text)) {
    return {
      kind: 'answer',
      text:
        allProducts.length
          ? allProducts
              .map(
                product =>
                  `${product.name}: ${product.stock} in stock`
              )
              .join('\n')
          : 'No products found.'
    };
  }


  /*
   * Specific customer balance.
   */
  const customerResult =
    resolveEntity(
      allCustomers,
      text,
      'customer'
    );

  if (
    customerResult.ambiguous &&
    RX.balance.test(text)
  ) {
    return {
      kind: 'clarification',
      text: customerResult.question
    };
  }

  if (
    customerResult.found &&
    RX.balance.test(text) &&
    !Number.isFinite(amountFrom(text))
  ) {
    rememberContext({
      customer: customerResult.item
    });

    return {
      kind: 'answer',
      text:
        `${customerResult.item.name}: ` +
        `due ${money(
          customerResult.item.balance || 0
        )}.`
    };
  }


  /*
   * General customer dues.
   */
  if (
    (
      RX.customer.test(text) &&
      RX.balance.test(text)
    ) ||
    (
      RX.balance.test(text) &&
      /(?:udhaar|udhar|واجب|ادھار)/i.test(text)
    )
  ) {
    const due =
      allCustomers.filter(
        customer =>
          Number(customer.balance || 0) > 0
      );

    return {
      kind: 'answer',
      text:
        due.length
          ? due
              .map(
                customer =>
                  `${customer.name}: ${money(
                    customer.balance
                  )}`
              )
              .join('\n')
          : 'No customer dues found.'
    };
  }


  /*
   * Today's sales.
   */
  if (
    RX.sale.test(text) &&
    RX.today.test(text)
  ) {
    const date =
      todayDate();

    const rows =
      allSales.filter(
        sale =>
          dateMatches(
            sale.date,
            date
          )
      );

    const total =
      rows.reduce(
        (sum, sale) =>
          sum +
          Number(sale.total || 0),
        0
      );

    return {
      kind: 'answer',
      text:
        `Today's sales: ${rows.length} sale(s), ` +
        `total ${money(total)}.`
    };
  }


  /*
   * Yesterday's sales.
   */
  if (
    RX.sale.test(text) &&
    RX.yesterday.test(text)
  ) {
    const date =
      yesterdayDate();

    const rows =
      allSales.filter(
        sale =>
          dateMatches(
            sale.date,
            date
          )
      );

    const total =
      rows.reduce(
        (sum, sale) =>
          sum +
          Number(sale.total || 0),
        0
      );

    return {
      kind: 'answer',
      text:
        `Yesterday's sales: ${rows.length} sale(s), ` +
        `total ${money(total)}.`
    };
  }


  /*
   * Today's profit.
   */
  if (
    RX.profit.test(text) &&
    RX.today.test(text)
  ) {
    const date =
      todayDate();

    const rows =
      allSales.filter(
        sale =>
          dateMatches(
            sale.date,
            date
          )
      );

    const profit =
      rows.reduce(
        (sum, sale) =>
          sum +
          Number(
            sale.totalProfit || 0
          ),
        0
      );

    return {
      kind: 'answer',
      text:
        `Today's recorded profit: ${money(profit)}.`
    };
  }


  /*
   * Total expenses.
   */
  if (
    RX.expense.test(text) &&
    (
      RX.today.test(text) ||
      /total|kitna|how much|amount/i.test(text)
    )
  ) {
    let rows =
      expenses();

    if (RX.today.test(text)) {
      const today =
        todayDate();

      rows =
        rows.filter(
          expense =>
            dateMatches(
              expense.date,
              today
            )
        );
    }

    const total =
      rows.reduce(
        (sum, expense) =>
          sum +
          Number(expense.amount || 0),
        0
      );

    return {
      kind: 'answer',
      text:
        `Total expenses: ${money(total)}.`
    };
  }

  return null;
}


/* -------------------------------------------------------------------------- */
/* NATURAL-LANGUAGE ENTITY HELPERS                                           */
/* -------------------------------------------------------------------------- */

function extractPhone(text) {
  const match = String(text || '').match(
    /(?:phone|mobile|number|no\.?|فون|موبائل|نمبر)\s*(?:is|:|=)?\s*(\+?\d[\d\s().-]{5,}\d)/i
  );
  return match ? match[1].replace(/[\s().-]/g, '') : '';
}

function extractLabeledField(text, labels) {
  const label = labels.join('|');
  const match = String(text || '').match(
    new RegExp(`(?:${label})\\s*(?:is|:|=)?\\s*(.+?)(?=\\s+(?:and\\s+)?(?:phone|mobile|number|address|phone number|فون|موبائل|نمبر|پتہ)\\b|$)`, 'i')
  );
  return match ? match[1].trim().replace(/[,.،؛;]+$/, '') : '';
}

function parseCustomerFields(original) {
  const text = norm(original);
  let name = extractLabeledField(text, ['name', 'named', 'called', 'ka naam', 'naam', 'نام', 'کا نام']);
  if (!name) {
    const m = text.match(/(?:add|create|new|banao|banayen|بناؤ|بنائیں|شامل)\s+(?:a\s+)?(?:customer|client|grahak|گاہک)\s+(.+?)(?=\s+(?:and\s+)?(?:phone|mobile|number|address|نام|فون|موبائل|نمبر|پتہ)\b|$)/i);
    if (m) name = m[1].trim();
  }
  name = name.replace(/\b(?:phone|mobile|number|address|فون|موبائل|نمبر|پتہ)\b.*$/i, '').trim();
  const phone = extractPhone(original);
  const address = extractLabeledField(original, ['address', 'addr', 'پتہ']);
  return { name, phone, address };
}

function parseProductCreation(original) {
  const text = norm(original);
  const command = text.match(/^(?:please\s+)?(?:add|create|new|banao|banayen|بناؤ|بنائیں|شامل)\s+(?:a\s+)?(?:product|item|پروڈکٹ|آئٹم)\b/i);
  if (!command) return null;

  let rest = text.slice(command[0].length).trim();
  const getNum = pattern => {
    const m = text.match(pattern);
    return m ? Number(m[1].replace(/,/g, '')) : NaN;
  };
  const cost = getNum(/(?:cost|purchase\s+price|buying\s+price|لاگت|خرید)[^0-9]*(\d+(?:\.\d+)?)/i);
  const wholesalePrice = getNum(/(?:wholesale|wholesale\s+price)[^0-9]*(\d+(?:\.\d+)?)/i);
  const retailPrice = getNum(/(?:retail|retail\s+price)[^0-9]*(\d+(?:\.\d+)?)/i);
  const stock = getNum(/(?:stock|quantity|qty|pcs?|pieces?|اسٹاک|مقدار)[^0-9]*(\d+(?:\.\d+)?)/i);
  const minStock = getNum(/(?:min(?:imum)?\s+stock|low\s+stock)[^0-9]*(\d+(?:\.\d+)?)/i);
  const genericPrice = getNum(/(?:price|قیمت)[^0-9]*(\d+(?:\.\d+)?)/i);
  const barcode = (text.match(/(?:barcode|bar\s*code)[^0-9]*([0-9A-Za-z-]+)/i)||[])[1] || '';

  rest = rest
    .replace(/(?:cost|purchase\s+price|buying\s+price|wholesale(?:\s+price)?|retail(?:\s+price)?|price|stock|quantity|qty|pcs?|pieces?|min(?:imum)?\s+stock|low\s+stock|barcode|bar\s*code)\s*(?:is|:|=)?\s*[0-9A-Za-z.-]+/gi, ' ')
    .replace(/\s+(?:and|with|اور)\s+/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  if (!rest) return { name: '', cost, wholesalePrice, retailPrice, stock, minStock, barcode };
  const price = Number.isFinite(genericPrice) ? genericPrice : NaN;
  const wholesale = Number.isFinite(wholesalePrice) ? wholesalePrice : price;
  const retail = Number.isFinite(retailPrice) ? retailPrice : (Number.isFinite(price) ? price : wholesale);
  return { name: rest, cost, wholesalePrice: wholesale, retailPrice: retail, stock, minStock, barcode };
}

function extractSaleItems(text, list) {
  const source = norm(text);
  const found = [];
  for (const product of list || []) {
    if (!product?.name) continue;
    const name = norm(product.name);
    const re = new RegExp(`(^|\\s)${escapeRegex(name).replace(/\s+/g, '\\s+')}(?=\\s|$)`, 'i');
    const match = re.exec(source);
    if (!match) continue;
    const start = match.index + match[1].length;
    const before = source.slice(0, start).trim();
    const after = source.slice(start + name.length).trim();
    const beforeQty = before.match(/(?:^|\s)(\d+(?:\.\d+)?)\s*$/);
    const afterQty = after.match(/^(?:x\s*)?(\d+(?:\.\d+)?)(?=\s|$)/i);
    const qty = beforeQty ? Number(beforeQty[1]) : (afterQty ? Number(afterQty[1]) : 1);
    found.push({ product, qty: Math.max(1, Math.floor(qty)), index: start });
  }
  found.sort((a,b)=>a.index-b.index);
  const unique=[]; const seen=new Set();
  for(const item of found){ if(!seen.has(item.product.id)){seen.add(item.product.id);unique.push(item);} }
  return unique;
}

/* -------------------------------------------------------------------------- */
/* COMMAND PARSER                                                             */
/* -------------------------------------------------------------------------- */

function parseCommand(input) {
  const original = String(input || '').trim();
  const text = norm(original);

  if (!text) return null;

  const allProducts = products();
  const allCustomers = customers();
  const allSuppliers = suppliers();

  clearOldContext();

  // Explicit "add/create product" commands must never fall through to the
  // expense handler or stock-adjustment handler.
  const productCreation = parseProductCreation(original);
  if (productCreation) {
    if (!productCreation.name) {
      return { kind: 'clarification', text: 'What is the product name?' };
    }
    const existingProduct = allProducts.find(p => norm(p.name) === norm(productCreation.name));
    if (existingProduct) {
      return { kind: 'answer', text: `Product "${existingProduct.name}" already exists.` };
    }
    if (!Number.isFinite(productCreation.wholesalePrice) && !Number.isFinite(productCreation.retailPrice)) {
      return { kind: 'clarification', text: `What is the price of ${productCreation.name}? You can say: "add product ${productCreation.name}, price 2200, stock 5".` };
    }
    return {
      kind: 'confirm',
      action: {
        type: 'addProduct',
        name: productCreation.name,
        cost: Number.isFinite(productCreation.cost) ? productCreation.cost : 0,
        wholesalePrice: Number.isFinite(productCreation.wholesalePrice) ? productCreation.wholesalePrice : productCreation.retailPrice,
        retailPrice: Number.isFinite(productCreation.retailPrice) ? productCreation.retailPrice : productCreation.wholesalePrice,
        stock: Number.isFinite(productCreation.stock) ? productCreation.stock : 0,
        minStock: Number.isFinite(productCreation.minStock) ? productCreation.minStock : 5,
        barcode: productCreation.barcode || '',
        summary: `Create product "${productCreation.name}" with stock ${Number.isFinite(productCreation.stock) ? productCreation.stock : 0} and price ${money(Number.isFinite(productCreation.retailPrice) ? productCreation.retailPrice : productCreation.wholesalePrice)}?`
      }
    };
  }

  /*
   * First handle pure information requests.
   */
  const information =
    parseInformationCommand(original);

  if (information) {
    return information;
  }


  // Explicit customer creation captures all supplied fields in the same command.
  if (rx(WORDS.addCustomer).test(text) && RX.customer.test(text)) {
    const fields = parseCustomerFields(original);
    if (!fields.name) return { kind: 'clarification', text: 'What is the customer name?' };
    const duplicate = allCustomers.find(c => norm(c.name) === norm(fields.name));
    if (duplicate) return { kind: 'answer', text: `Customer "${duplicate.name}" already exists.` };
    return {
      kind: 'confirm',
      action: {
        type: 'addCustomer',
        name: fields.name,
        phone: fields.phone,
        address: fields.address,
        summary: `Create customer "${fields.name}"${fields.phone ? ` with phone ${fields.phone}` : ''}${fields.address ? ` and address "${fields.address}"` : ''}?`
      }
    };
  }

  /*
   * Resolve entities.
   */
  let productResult =
    resolveEntity(
      allProducts,
      text,
      'product'
    );

  let customerResult =
    resolveEntity(
      allCustomers,
      text,
      'customer'
    );

  let supplierResult =
    resolveEntity(
      allSuppliers,
      text,
      'supplier'
    );


  /*
   * Use short-term context for follow-up commands.
   *
   * "Pepsi 1.5L ka stock batao"
   * "10 aur add karo"
   */
  const hasProductVerb =
    rx(
      WORDS.addStock
        .concat(WORDS.removeStock)
        .concat(WORDS.sellProduct)
    ).test(text);

  if (
    !productResult.found &&
    hasProductVerb &&
    contextProduct()
  ) {
    productResult = {
      found: true,
      ambiguous: false,
      item: contextProduct(),
      matches: [contextProduct()]
    };
  }

  if (
    !customerResult.found &&
    (
      rx(
        WORDS.receiveCustomer
          .concat(WORDS.giveCustomer)
      ).test(text) ||
      /(?:same customer|this customer|that customer|usi customer|is customer|اس گاہک|اسی گاہک)/i.test(text)
    ) &&
    contextCustomer()
  ) {
    customerResult = {
      found: true,
      ambiguous: false,
      item: contextCustomer(),
      matches: [contextCustomer()]
    };
  }

  if (
    !supplierResult.found &&
    rx(
      WORDS.supplierPayment
        .concat(WORDS.supplierDebt)
    ).test(text) &&
    contextSupplier()
  ) {
    supplierResult = {
      found: true,
      ambiguous: false,
      item: contextSupplier(),
      matches: [contextSupplier()]
    };
  }


  /*
   * Ambiguous product.
   */
  if (
    productResult.ambiguous &&
    (
      RX.stock.test(text) ||
      (!rx(WORDS.sellProduct).test(text) && hasProductVerb)
    )
  ) {
    return {
      kind: 'clarification',
      text: productResult.question
    };
  }


  /*
   * Ambiguous customer.
   */
  if (
    customerResult.ambiguous &&
    (
      RX.balance.test(text) ||
      rx(
        WORDS.receiveCustomer
          .concat(WORDS.giveCustomer)
      ).test(text)
    )
  ) {
    return {
      kind: 'clarification',
      text: customerResult.question
    };
  }


  /*
   * Ambiguous supplier.
   */
  if (
    supplierResult.ambiguous &&
    rx(
      WORDS.supplierPayment
        .concat(WORDS.supplierDebt)
    ).test(text)
  ) {
    return {
      kind: 'clarification',
      text: supplierResult.question
    };
  }


  /*
   * ------------------------------------------------------------------------
   * SELL — supports one or many products in the same command.
   * Examples:
   *   "sell 1 lamp"
   *   "1 lamp 3 frame 5 gop retail pa sale karo"
   *   "lamp becho"
   * ------------------------------------------------------------------------
   */

  if (rx(WORDS.sellProduct).test(text) || (RX.sale.test(text) && productResult.found)) {
    const saleItems = extractSaleItems(text, allProducts);

    if (!saleItems.length && productResult.found) {
      saleItems.push({ product: productResult.item, qty: qtyFrom(text) });
    }

    if (!saleItems.length) {
      return {
        kind: 'clarification',
        text: 'Which product should I sell? You can say: "sell 1 lamp" or "1 lamp 3 frame retail sale".'
      };
    }

    const invalid = saleItems.find(item => Number(item.qty) > (Number(item.product.stock) || 0));
    if (invalid) {
      return { kind: 'answer', text: `Not enough stock for ${invalid.product.name}. Available: ${Number(invalid.product.stock) || 0}.` };
    }

    const saleType = /(?:retail|retail sale|retail pa|ریٹیل)/i.test(text) ? 'retail' : 'wholesale';
    const customer = customerResult.found ? customerResult.item : null;
    const total = saleItems.reduce((sum, item) => {
      const unit = saleType === 'retail'
        ? Number(item.product.retailPrice ?? item.product.price ?? 0)
        : Number(item.product.wholesalePrice ?? item.product.price ?? 0);
      return sum + unit * Number(item.qty);
    }, 0);

    rememberContext({
      product: saleItems.length === 1 ? saleItems[0].product : undefined,
      customer: customer || undefined
    });

    return {
      kind: 'confirm',
      action: {
        type: saleItems.length === 1 ? 'sellProduct' : 'sellProducts',
        items: saleItems.map(item => ({ product: item.product, qty: item.qty })),
        product: saleItems.length === 1 ? saleItems[0].product : undefined,
        qty: saleItems.length === 1 ? saleItems[0].qty : undefined,
        customer,
        saleType,
        summary:
          `${saleType === 'retail' ? 'Retail' : 'Wholesale'} sale: ` +
          `${saleItems.map(item => `${item.qty} x ${item.product.name}`).join(', ')}` +
          `${customer ? ` for ${customer.name}` : ''} — total ${money(total)}?`
      }
    };
  }

  /*
   * ------------------------------------------------------------------------
   * STOCK ADD
   * ------------------------------------------------------------------------
   */

  if (
    productResult.found &&
    rx(WORDS.addStock).test(text) &&
    (
      RX.stock.test(text) ||
      RX.quantity.test(text)
    )
  ) {
    const product =
      productResult.item;

    const qty =
      qtyFrom(text);

    if (!Number.isFinite(qty) || qty <= 0) {
      return {
        kind: 'clarification',
        text:
          `How many ${product.name} should I add?`
      };
    }

    rememberContext({
      product
    });

    return {
      kind: 'confirm',
      action: {
        type: 'addStock',
        product,
        qty,
        summary:
          `Add ${qty} to ${product.name} stock? ` +
          `Current stock: ${Number(product.stock) || 0}.`
      }
    };
  }


  /*
   * ------------------------------------------------------------------------
   * STOCK REMOVE
   * ------------------------------------------------------------------------
   */

  if (
    productResult.found &&
    rx(WORDS.removeStock).test(text) &&
    (
      RX.stock.test(text) ||
      RX.quantity.test(text)
    )
  ) {
    const product =
      productResult.item;

    const qty =
      qtyFrom(text);

    if (!Number.isFinite(qty) || qty <= 0) {
      return {
        kind: 'clarification',
        text:
          `How many ${product.name} should I remove?`
      };
    }

    rememberContext({
      product
    });

    return {
      kind: 'confirm',
      action: {
        type: 'removeStock',
        product,
        qty,
        summary:
          `Remove ${qty} from ${product.name} stock? ` +
          `Current stock: ${Number(product.stock) || 0}.`
      }
    };
  }


  /*
   * ------------------------------------------------------------------------
   * CUSTOMER PAYMENT
   * ------------------------------------------------------------------------
   */

  const receiveWords =
    rx(WORDS.receiveCustomer);

  const giveWords =
    rx(WORDS.giveCustomer);

  /*
   * "udhaar liya" means the customer took credit.
   * Therefore it must not accidentally become "received payment".
   */
  const isCreditPhrase =
    /(?:udhaar|udhar|qarz|ادھار|قرض)/i.test(text);

  if (
    customerResult.found &&
    receiveWords.test(text) &&
    !isCreditPhrase
  ) {
    const amount =
      amountFrom(text);

    if (!Number.isFinite(amount)) {
      return {
        kind: 'clarification',
        text:
          `How much should I receive from ${customerResult.item.name}?`
      };
    }

    const current =
      Math.max(
        0,
        Number(
          customerResult.item.balance
        ) || 0
      );

    if (amount > current) {
      return {
        kind: 'answer',
        text:
          `${customerResult.item.name}'s current due is ` +
          `${money(current)}. ` +
          `The requested payment of ${money(amount)} ` +
          `is greater than the due.`
      };
    }

    rememberContext({
      customer: customerResult.item
    });

    return {
      kind: 'confirm',
      action: {
        type: 'receiveCustomer',
        customer: customerResult.item,
        amount,
        summary:
          `Receive ${money(amount)} from ` +
          `${customerResult.item.name}? ` +
          `Current due: ` +
          `${money(current)}.`
      }
    };
  }


  /*
   * ------------------------------------------------------------------------
   * CUSTOMER CREDIT
   * ------------------------------------------------------------------------
   */

  if (
    customerResult.found &&
    giveWords.test(text)
  ) {
    const amount =
      amountFrom(text);

    if (!Number.isFinite(amount)) {
      return {
        kind: 'clarification',
        text:
          `How much credit should I add to ${customerResult.item.name}?`
      };
    }

    const current =
      Math.max(
        0,
        Number(
          customerResult.item.balance
        ) || 0
      );

    rememberContext({
      customer: customerResult.item
    });

    return {
      kind: 'confirm',
      action: {
        type: 'giveCustomer',
        customer: customerResult.item,
        amount,
        summary:
          `Add ${money(amount)} to ` +
          `${customerResult.item.name}'s due? ` +
          `Current due: ${money(current)}.`
      }
    };
  }


  /*
   * ------------------------------------------------------------------------
   * SUPPLIER PAYMENT
   * ------------------------------------------------------------------------
   */

  const supplierPay =
    rx(WORDS.supplierPayment);

  if (
    supplierResult.found &&
    supplierPay.test(text)
  ) {
    const amount =
      amountFrom(text);

    if (!Number.isFinite(amount)) {
      return {
        kind: 'clarification',
        text:
          `How much should I pay ${supplierResult.item.name}?`
      };
    }

    const current =
      Math.max(
        0,
        Number(
          supplierResult.item.balance
        ) || 0
      );

    if (amount > current) {
      return {
        kind: 'answer',
        text:
          `${supplierResult.item.name}'s current payable is ` +
          `${money(current)}. ` +
          `The requested payment is ${money(amount)}.`
      };
    }

    rememberContext({
      supplier: supplierResult.item
    });

    return {
      kind: 'confirm',
      action: {
        type: 'supplierPayment',
        supplier: supplierResult.item,
        amount,
        summary:
          `Pay ${money(amount)} to ` +
          `${supplierResult.item.name}? ` +
          `Current payable: ${money(current)}.`
      }
    };
  }


  /*
   * ------------------------------------------------------------------------
   * SUPPLIER DEBT
   * ------------------------------------------------------------------------
   */

  if (
    supplierResult.found &&
    rx(WORDS.supplierDebt).test(text)
  ) {
    const amount =
      amountFrom(text);

    if (!Number.isFinite(amount)) {
      return {
        kind: 'clarification',
        text:
          `How much payable should I add for ${supplierResult.item.name}?`
      };
    }

    const current =
      Math.max(
        0,
        Number(
          supplierResult.item.balance
        ) || 0
      );

    rememberContext({
      supplier: supplierResult.item
    });

    return {
      kind: 'confirm',
      action: {
        type: 'supplierDebt',
        supplier: supplierResult.item,
        amount,
        summary:
          `Add ${money(amount)} payable to ` +
          `${supplierResult.item.name}? ` +
          `Current payable: ${money(current)}.`
      }
    };
  }


  /*
   * ------------------------------------------------------------------------
   * EXPENSE
   * ------------------------------------------------------------------------
   */

  if (rx(WORDS.expense).test(text)) {
    const amount =
      amountFrom(text);

    if (!Number.isFinite(amount)) {
      return {
        kind: 'clarification',
        text:
          'How much is the expense?'
      };
    }

    return {
      kind: 'confirm',
      action: {
        type: 'expense',
        amount,
        category: 'AI expense',
        note: original,
        summary:
          `Record an expense of ${money(amount)}?`
      }
    };
  }


  /*
   * ------------------------------------------------------------------------
   * CREATE PRODUCT
   * ------------------------------------------------------------------------
   *
   * Kept conservative because the existing product model has several
   * price fields. Do not create a product unless the user gives enough
   * information.
   */

  if (
    rx(WORDS.addProduct).test(text) &&
    /(?:product|item|پروڈکٹ|آئٹم)/i.test(text)
  ) {
    return {
      kind: 'clarification',
      text:
        'Please provide the product name and its price before I create it.'
    };
  }


  /*
   * ------------------------------------------------------------------------
   * FOLLOW-UP: "receive it", "pay him", "add more", etc.
   * ------------------------------------------------------------------------
   */

  const context =
    getContext();

  if (
    context.customer &&
    /^(?:receive it|receive|collect it|liya|le liya|وصول کرلو)$/i.test(text)
  ) {
    return {
      kind: 'clarification',
      text:
        `How much should I receive from ${context.customer.name}?`
    };
  }

  if (
    context.product &&
    /^(?:add more|add aur|aur add karo|aur daal do|مزید شامل کرو)$/i.test(text)
  ) {
    return {
      kind: 'clarification',
      text:
        `How many more ${context.product.name} should I add?`
    };
  }


  return null;
}


/* -------------------------------------------------------------------------- */
/* MULTI-ACTION SUPPORT                                                       */
/* -------------------------------------------------------------------------- */

/*
 * Split simple commands joined with "and / aur / phir".
 *
 * We deliberately keep this conservative. A complex sentence should not be
 * executed partially unless every part can be understood.
 */
function splitMultiCommand(input) {
  const text =
    String(input || '').trim();

  if (!text) return [];

  const parts =
    text
      .split(
        /\s+(?:and|aur|phir|then|اور|پھر)\s+/i
      )
      .map(x => x.trim())
      .filter(Boolean);

  return parts.length > 1
    ? parts
    : [];
}


/* -------------------------------------------------------------------------- */
/* PUBLIC AGENT HANDLER                                                       */
/* -------------------------------------------------------------------------- */

export async function handleAgentCommand(input) {
  const text =
    String(input || '').trim();

  if (!text) {
    return {
      handled: true,
      text: 'Please enter a command.'
    };
  }

  clearOldContext();


  /*
   * Pending confirmation has absolute priority.
   *
   * This prevents:
   * "Add 10 Pepsi"
   * "yes"
   *
   * from being interpreted as a completely new command.
   */
  if (window.__myBusinessAiPending) {
    const pending =
      window.__myBusinessAiPending;

    if (isYes(text)) {
      window.__myBusinessAiPending = null;

      try {
        const result =
          await execute(pending);

        return {
          handled: true,
          text: result
        };
      } catch (error) {
        return {
          handled: true,
          text:
            `I could not complete that task: ` +
            `${error?.message || error}`
        };
      }
    }

    if (isNo(text)) {
      window.__myBusinessAiPending = null;

      return {
        handled: true,
        text:
          'Cancelled. No changes were made.'
      };
    }

    return {
      handled: true,
      text:
        'Please reply "yes" to confirm or "no" to cancel.'
    };
  }


  /*
   * Try deterministic parser first.
   */
  const parsed =
    parseCommand(text);

  if (parsed?.kind === 'answer') {
    return {
      handled: true,
      text: parsed.text
    };
  }

  if (parsed?.kind === 'clarification') {
    return {
      handled: true,
      text: parsed.text
    };
  }

  if (parsed?.kind === 'confirm') {
    return {
      handled: true,
      text: confirmationText(parsed.action),
      confirmation: { yes: 'Yes', no: 'No' }
    };
  }


  /*
   * Simple multi-action detection.
   *
   * We do not automatically execute several financial operations here.
   * The surrounding Qwen layer can interpret complex requests and call this
   * deterministic layer one validated action at a time.
   */
  const multi =
    splitMultiCommand(text);

  if (multi.length > 1) {
    const parsedParts =
      multi.map(part =>
        parseCommand(part)
      );

    const unsupported =
      parsedParts.some(
        part =>
          !part ||
          !['answer', 'confirm', 'clarification']
            .includes(part.kind)
      );

    if (!unsupported) {
      const clarifications =
        parsedParts.filter(
          part =>
            part.kind === 'clarification'
        );

      if (clarifications.length) {
        return {
          handled: true,
          text:
            clarifications
              .map(x => x.text)
              .join('\n')
        };
      }

      const answers =
        parsedParts.filter(
          part =>
            part.kind === 'answer'
        );

      if (
        answers.length ===
        parsedParts.length
      ) {
        return {
          handled: true,
          text:
            answers
              .map(x => x.text)
              .join('\n')
        };
      }

      /*
       * Multiple mutating operations are deliberately not executed
       * automatically by this layer because one confirmation must cover
       * the complete operation set.
       */
      const actions =
        parsedParts
          .filter(
            part =>
              part.kind === 'confirm'
          )
          .map(
            part =>
              part.action
          );

      if (actions.length) {
        return {
          handled: true,
          text:
            'I understood multiple actions, but I need to process them one at a time to keep the business data safe.'
        };
      }
    }
  }


  /*
   * Nothing deterministic was understood.
   *
   * The surrounding Qwen layer can now handle language interpretation,
   * explanation, navigation, or another natural-language response.
   */
  return {
    handled: false
  };
}


/* -------------------------------------------------------------------------- */
/* QWEN / AGENT CONTEXT                                                       */
/* -------------------------------------------------------------------------- */

export function agentContext() {
  const data =
    window.data || {};

  const context =
    getContext();

  return [
    'MyBusiness local agent context:',
    `Products: ${data.products?.length || 0}`,
    `Customers: ${data.customers?.length || 0}`,
    `Suppliers: ${data.suppliers?.length || 0}`,
    `Sales: ${data.sales?.length || 0}`,
    `Expenses: ${data.expenses?.length || 0}`,

    `Product names: ${names(data.products || [], 20) || 'none'}`,
    `Customer names: ${names(data.customers || [], 20) || 'none'}`,
    `Supplier names: ${names(data.suppliers || [], 20) || 'none'}`,

    context.product
      ? `Current product context: ${context.product.name}`
      : '',

    context.customer
      ? `Current customer context: ${context.customer.name}`
      : '',

    context.supplier
      ? `Current supplier context: ${context.supplier.name}`
      : '',

    `Language: ${document.documentElement.lang || 'en'}`,

    'Registered actions:',
    Object.keys(ACTIONS).join(', '),

    'Safety:',
    'Never execute arbitrary JavaScript.',
    'Never invent database values.',
    'Never invent IDs.',
    'Never bypass ownerId checks.',
    'Use JavaScript for financial calculations.',
    'Ask for clarification when an entity is ambiguous.'
  ]
    .filter(Boolean)
    .join('\n');
}


/* -------------------------------------------------------------------------- */
/* OPTIONAL DEBUG ACCESS                                                      */
/* -------------------------------------------------------------------------- */

export function getAgentState() {
  const context =
    getContext();

  return {
    pending:
      Boolean(
        window.__myBusinessAiPending
      ),

    pendingAction:
      window.__myBusinessAiPending
        ? {
            type:
              window.__myBusinessAiPending.type
          }
        : null,

    context: {
      product:
        context.product?.name || null,

      customer:
        context.customer?.name || null,

      supplier:
        context.supplier?.name || null,

      lastAction:
        context.lastAction?.type || null
    }
  };
}