/* MyBusiness browser-local Qwen3 0.6B AI agent.
 * Uses Transformers.js + ONNX/WebGPU in the browser. No cloud inference.
 * Business data is passed only to the local model for intent parsing; writes go through validated tools.
 */
import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm';

env.allowRemoteModels = true;
env.allowLocalModels = true;
env.useBrowserCache = true;

const MODEL_ID = 'onnx-community/Qwen3-0.6B-ONNX';
const MODEL_DTYPE = 'q4f16';
const MODEL_LABEL = 'Qwen3 0.6B';
const WRITE_TOOLS = new Set(['add_product','update_product','add_stock','create_sale','create_credit_sale','receive_customer_payment','record_customer_credit','create_purchase','record_supplier_payment','record_expense']);
const TOOLS = {
 search_products:{d:'Find products by name or barcode.',r:['query']}, get_product:{d:'Get one exact product.',r:['query']}, get_low_stock_products:{d:'List low-stock products.',r:[]},
 search_customers:{d:'Find customers by name or phone.',r:['query']}, get_customer_balance:{d:'Get one customer balance.',r:['customer']},
 search_suppliers:{d:'Find suppliers by name or phone.',r:['query']}, get_supplier_balance:{d:'Get one supplier balance.',r:['supplier']},
 get_today_sales:{d:"Get today's sales.",r:[]}, get_sales_summary:{d:'Summarize sales.',r:['from','to']}, get_purchase_summary:{d:'Summarize purchases.',r:['from','to']},
 get_cashbook_summary:{d:'Summarize cashbook.',r:['from','to']}, get_expense_summary:{d:'Summarize expenses.',r:['from','to']}, get_stock_summary:{d:'Summarize stock.',r:[]},
 add_product:{d:'Add a product.',r:['name','cost','wholesalePrice','retailPrice','stock']}, update_product:{d:'Update a product by exact id.',r:['id']}, add_stock:{d:'Add stock to an existing product.',r:['product','quantity']},
 create_sale:{d:'Create a sale.',r:['items','saleType','amountPaid']}, create_credit_sale:{d:'Create a credit sale.',r:['customer','items','saleType','amountPaid']},
 receive_customer_payment:{d:'Record money received from a customer.',r:['customer','amount']}, record_customer_credit:{d:'Record customer credit.',r:['customer','amount']},
 create_purchase:{d:'Create a stock purchase.',r:['items','amountPaid']}, record_supplier_payment:{d:'Record supplier payment.',r:['supplier','amount']}, record_expense:{d:'Record an expense.',r:['amount','category']}
};
let generator=null, loadingPromise=null, pendingWrite=null, busy=false;

const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>window.formatCurrency?window.formatCurrency(Number(v)||0):`Rs. ${(Number(v)||0).toLocaleString()}`;
function today(){return new Date().toISOString().slice(0,10)}
function setStatus(text,cls=''){const e=$('mybiz-ai-status');if(e){e.textContent=text;e.className=cls}}
function progress(text){const e=$('mybiz-ai-progress');if(e)e.textContent=text||''}
function modelPrompt(userText){const schemas=Object.entries(TOOLS).map(([n,x])=>`${n}(${x.r.join(',')||'none'}): ${x.d}`).join('\n');return `You are the MyBusiness command parser. Do not reason aloud. Output ONLY valid JSON. Never invent customer/product/supplier names, IDs, prices, balances or quantities. Use the user's wording for names; the application validates them. For dates use YYYY-MM-DD. For Roman Urdu, infer the intended business action. If information is missing, use {"tool":"clarify","arguments":{"question":"..."}}.\nTOOLS:\n${schemas}\nJSON: {"tool":"name","arguments":{}}\nUSER: ${userText}`}
function parseJSON(text){let s=String(text||'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/```json|```/gi,'').trim();const a=s.indexOf('{');if(a<0)return null;let depth=0,str=false,escp=false;for(let i=a;i<s.length;i++){const c=s[i];if(str){if(escp)escp=false;else if(c==='\\')escp=true;else if(c==='"')str=false;continue}if(c==='"'){str=true;continue}if(c==='{')depth++;if(c==='}'&&--depth===0){try{return JSON.parse(s.slice(a,i+1))}catch{return null}}}return null}
function fallbackIntent(t){const l=t.toLowerCase();if(/low stock|kam stock|کم اسٹاک/.test(l))return {tool:'get_low_stock_products',arguments:{}};let m=t.match(/(.+?)\s+(?:ka|ki|ke)\s+balance/i);if(m)return {tool:'get_customer_balance',arguments:{customer:m[1].trim()}};m=t.match(/(.+?)\s+(?:se)\s+(?:rs\.?\s*)?([\d,]+)\s*(?:receive|liye|liya|mile)/i)||t.match(/(?:receive|received)\s+(.+?)\s+(?:rs\.?\s*)?([\d,]+)/i);if(m)return {tool:'receive_customer_payment',arguments:{customer:m[1].trim(),amount:Number(m[2].replace(/,/g,''))}};if(/today.*sale|aaj.*sale/.test(l))return {tool:'get_today_sales',arguments:{}};return null}

async function loadModel(){if(generator)return generator;if(loadingPromise)return loadingPromise;if(!navigator.gpu){setStatus('WebGPU not available');throw new Error('This browser does not support WebGPU. Use a recent Chrome/Edge browser for local Qwen AI.');}
 loadingPromise=(async()=>{setStatus('Downloading Qwen3 0.6B…');progress('First-time setup: downloading the local AI model. Keep this tab open.');
   const g=await pipeline('text-generation',MODEL_ID,{device:'webgpu',dtype:MODEL_DTYPE,progress_callback:p=>{if(typeof p?.progress==='number'){const pct=Math.max(0,Math.min(100,p.progress));progress(`AI model: ${pct.toFixed(0)}%`);setStatus(`Downloading Qwen3 0.6B ${pct.toFixed(0)}%`)}}});
   generator=g;setStatus('Qwen3 0.6B ready • offline');progress('Model is installed in this browser. AI inference is local.');return g;
 })().catch(e=>{loadingPromise=null;generator=null;setStatus('AI setup failed');progress('Download/initialization failed. Tap Retry or check the browser/network.');throw e});return loadingPromise}
async function infer(text){const g=await loadModel();setStatus('Qwen3 0.6B • processing locally');const out=await g([{role:'system',content:'Return only the requested JSON. Do not include <think>.'},{role:'user',content:modelPrompt(text)}],{max_new_tokens:220,do_sample:false,return_full_text:false});const raw=out?.[0]?.generated_text;const content=Array.isArray(raw)?raw.at(-1)?.content:raw;return parseJSON(content)}
function resolveOne(arr,q,label){const s=String(q||'').trim().toLowerCase();if(!s)throw new Error(`${label} is required.`);const exact=arr.filter(x=>String(x.name||'').trim().toLowerCase()===s||String(x.id||'').toLowerCase()===s);if(exact.length===1)return exact[0];if(exact.length>1)throw new Error(`I found multiple ${label}s named ${q}. Please select one.`);const partial=arr.filter(x=>String(x.name||'').toLowerCase().includes(s)||String(x.phone||'').toLowerCase().includes(s));if(partial.length===1)return partial[0];if(partial.length>1)throw new Error(`I found ${partial.length} matching ${label}s. Please be more specific.`);throw new Error(`${label} not found: ${q}`)}
function range(a){const from=a.from||today(),to=a.to||from;if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to))throw new Error('Invalid date. Use YYYY-MM-DD.');return [new Date(from+'T00:00:00'),new Date(to+'T23:59:59.999')]}
async function runTool(name,a={}){const d=window.data||{};switch(name){
 case 'search_products':return (d.products||[]).filter(p=>String(p.name||'').toLowerCase().includes(String(a.query||'').toLowerCase())||String(p.barcode||'')===String(a.query||'')).map(p=>({id:p.id,name:p.name,stock:+p.stock||0,cost:+p.cost||0,wholesalePrice:+(p.wholesalePrice??p.price)||0,retailPrice:+(p.retailPrice??p.price)||0}));
 case 'get_product':{const p=resolveOne(d.products||[],a.query,'product');return {id:p.id,name:p.name,stock:+p.stock||0,cost:+p.cost||0,wholesalePrice:+(p.wholesalePrice??p.price)||0,retailPrice:+(p.retailPrice??p.price)||0}}
 case 'get_low_stock_products':return (d.products||[]).filter(p=>(+p.stock||0)<=(+p.minStock||5)).map(p=>({name:p.name,stock:+p.stock||0,minStock:+p.minStock||5}));
 case 'search_customers':return (d.customers||[]).filter(c=>String(c.name||'').toLowerCase().includes(String(a.query||'').toLowerCase())||String(c.phone||'').includes(String(a.query||''))).map(c=>({id:c.id,name:c.name,phone:c.phone||'',balance:+c.balance||0}));
 case 'get_customer_balance':{const c=resolveOne(d.customers||[],a.customer,'customer');return {name:c.name,balance:+c.balance||0}}
 case 'search_suppliers':return (d.suppliers||[]).filter(s=>String(s.name||'').toLowerCase().includes(String(a.query||'').toLowerCase())||String(s.phone||'').includes(String(a.query||''))).map(s=>({id:s.id,name:s.name,phone:s.phone||'',balance:+s.balance||0}));
 case 'get_supplier_balance':{const s=resolveOne(d.suppliers||[],a.supplier,'supplier');return {name:s.name,balance:+s.balance||0}}
 case 'get_today_sales':{const [f,t]=range({});return (d.sales||[]).filter(s=>{const x=new Date(s.date);return x>=f&&x<=t}).map(s=>({invoiceNumber:s.invoiceNumber,total:+s.total||0,amountPaid:+s.amountPaid||0,amountDue:+s.amountDue||0,customerName:s.customerName||'Walk-in'}))}
 case 'get_sales_summary':{const [f,t]=range(a),r=(d.sales||[]).filter(s=>{const x=new Date(s.date);return x>=f&&x<=t});return {from:a.from,to:a.to,count:r.length,total:r.reduce((n,s)=>n+(+s.total||0),0),paid:r.reduce((n,s)=>n+(+s.amountPaid||0),0),due:r.reduce((n,s)=>n+(+s.amountDue||0),0),profit:r.reduce((n,s)=>n+(+s.totalProfit||0),0)}}
 case 'get_purchase_summary':{const [f,t]=range(a),r=(d.stockPurchases||[]).filter(s=>{const x=new Date(s.date);return x>=f&&x<=t});return {from:a.from,to:a.to,count:r.length,total:r.reduce((n,s)=>n+(+s.amount||0),0),paid:r.reduce((n,s)=>n+(+s.amountPaid||0),0),due:r.reduce((n,s)=>n+(+s.amountDue||0),0)}}
 case 'get_expense_summary':{const [f,t]=range(a),r=(d.expenses||[]).filter(s=>{const x=new Date(s.date);return x>=f&&x<=t});return {from:a.from,to:a.to,count:r.length,total:r.reduce((n,s)=>n+(+s.amount||0),0)}}
 case 'get_stock_summary':return {products:(d.products||[]).length,units:(d.products||[]).reduce((n,p)=>n+(+p.stock||0),0),lowStock:(d.products||[]).filter(p=>(+p.stock||0)<=(+p.minStock||5)).length};
 default: throw new Error(`Tool ${name} is not available in the browser build yet.`)
}}
function format(tool,r){if(tool==='get_customer_balance')return `${r.name} balance: ${money(r.balance)}.`;if(tool==='get_supplier_balance')return `${r.name} payable: ${money(r.balance)}.`;if(tool==='get_low_stock_products')return r.length?`Low stock: ${r.map(x=>`${x.name} (${x.stock})`).join(', ')}`:'No low-stock products.';if(tool==='get_today_sales')return r.length?`Today: ${money(r.reduce((n,x)=>n+x.total,0))} across ${r.length} invoices.`:'No sales today.';if(tool==='get_sales_summary')return `${aDate(r.from)} to ${aDate(r.to)}: ${r.count} sales, total ${money(r.total)}, paid ${money(r.paid)}, due ${money(r.due)}, profit ${money(r.profit)}.`;if(tool==='get_stock_summary')return `${r.products} products, ${r.units} units, ${r.lowStock} low-stock.`;return Array.isArray(r)?(r.length?JSON.stringify(r):'No matching records.'):JSON.stringify(r)}
function aDate(x){return x||today()}
function showConfirm(req){pendingWrite=req;const box=$('mybiz-ai-confirm');box.classList.remove('hidden');box.innerHTML=`<div><strong>Confirm action</strong><p>${esc(describe(req))}</p></div><div><button class="btn btn-secondary" id="ai-cancel">Cancel</button><button class="btn" id="ai-confirm">Confirm</button></div>`;$('ai-cancel').onclick=cancelAI;$('ai-confirm').onclick=confirmAI}
function describe(r){const a=r.arguments||{};return ({receive_customer_payment:`Record ${money(a.amount)} received from ${a.customer}.`,record_customer_credit:`Record ${money(a.amount)} credit for ${a.customer}.`,record_supplier_payment:`Record ${money(a.amount)} payment to ${a.supplier}.`,add_stock:`Add ${a.quantity} units of ${a.product} to stock.`,record_expense:`Record ${money(a.amount)} expense for ${a.category}.`,add_product:`Add product ${a.name}.`,update_product:`Update product ${a.id}.`,create_sale:`Create a ${a.saleType||'wholesale'} sale.`,create_credit_sale:`Create a credit sale for ${a.customer}.`,create_purchase:'Record this stock purchase.'}[r.tool]||`Run ${r.tool}.`)}
async function handle(req){if(!req||typeof req.tool!=='string')throw new Error('Invalid AI tool request.');if(req.tool==='clarify'){add('assistant',req.arguments?.question||'Please clarify.');return}if(!TOOLS[req.tool])throw new Error('Unknown tool rejected.');for(const k of TOOLS[req.tool].r)if(req.arguments?.[k]===undefined||req.arguments?.[k]==='')throw new Error(`Missing: ${k}`);if(WRITE_TOOLS.has(req.tool)){showConfirm(req);return}const r=await runTool(req.tool,req.arguments);add('assistant',format(req.tool,r))}
async function sendAI(){if(busy)return;const input=$('mybiz-ai-input'),text=input?.value.trim();if(!text)return;input.value='';add('user',text);busy=true;$('mybiz-ai-send').disabled=true;try{let req;try{req=await infer(text)}catch(e){if(/WebGPU/.test(e.message))throw e;req=fallbackIntent(text)}if(!req)throw new Error('I could not understand that request. Try a simpler English or Roman Urdu command.');await handle(req)}catch(e){add('assistant',e.message||'AI request failed.')}finally{busy=false;$('mybiz-ai-send').disabled=false;setStatus(generator?'Qwen3 0.6B ready • offline':'AI ready to start')}}
async function confirmAI(){const r=pendingWrite;if(!r)return;pendingWrite=null;$('mybiz-ai-confirm').classList.add('hidden');try{const result=await runTool(r.tool,r.arguments);add('assistant','Done. '+format(r.tool,result));window.dispatchEvent(new CustomEvent('mybusiness-ai-data-changed'));}catch(e){add('assistant',e.message||'Action failed.')}}
function cancelAI(){pendingWrite=null;$('mybiz-ai-confirm')?.classList.add('hidden');add('assistant','Cancelled.')}
function add(role,text){const b=$('mybiz-ai-messages');if(!b)return;const e=document.createElement('div');e.className=`mybiz-ai-msg ${role}`;e.innerHTML=esc(text).replace(/\n/g,'<br>');b.appendChild(e);b.scrollTop=b.scrollHeight}
function ensureUI(){if($('mybiz-ai-fab'))return;const fab=document.createElement('button');fab.id='mybiz-ai-fab';fab.className='mybiz-ai-fab';fab.innerHTML='<i class="fas fa-robot"></i><span>AI</span>';fab.onclick=openAI;document.body.appendChild(fab);const p=document.createElement('div');p.id='mybiz-ai-panel';p.className='mybiz-ai-panel hidden';p.innerHTML=`<div class="mybiz-ai-head"><div><strong>MyBusiness AI</strong><small id="mybiz-ai-status">Local Qwen3 0.6B • first setup on first use</small><small id="mybiz-ai-progress"></small></div><button id="mybiz-ai-close">&times;</button></div><div id="mybiz-ai-messages" class="mybiz-ai-messages"></div><div id="mybiz-ai-confirm" class="mybiz-ai-confirm hidden"></div><div class="mybiz-ai-input"><textarea id="mybiz-ai-input" rows="2" placeholder="Ask in English or Roman Urdu…"></textarea><button id="mybiz-ai-send"><i class="fas fa-paper-plane"></i></button></div>`;document.body.appendChild(p);$('mybiz-ai-close').onclick=closeAI;$('mybiz-ai-send').onclick=sendAI;$('mybiz-ai-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendAI()}});setStatus(navigator.gpu?'Qwen3 0.6B • local browser AI':'WebGPU unavailable')}
function openAI(){ensureUI();$('mybiz-ai-panel').classList.remove('hidden');$('mybiz-ai-input')?.focus()}
function closeAI(){$('mybiz-ai-panel')?.classList.add('hidden')}
window.openMyBusinessAI=openAI;window.closeMyBusinessAI=closeAI;window.sendMyBusinessAI=sendAI;window.confirmMyBusinessAI=confirmAI;window.cancelMyBusinessAI=cancelAI;
window.addEventListener('DOMContentLoaded',ensureUI);setTimeout(ensureUI,1000);
