export function calculateReportData(startDate, endDate) {
    const data = window.data;
    let totalSales = 0, knownProfit = 0, unknownCount = 0, txCount = 0; let totalExpenses = 0, totalStockPurchases = 0, customerPayments = 0, newDebt = 0;
    data.sales.forEach(s => { const d = new Date(s.date); if (d >= startDate && d <= endDate) { totalSales += (s.total || 0); if (s.profitKnown) knownProfit += (s.totalProfit || 0); else unknownCount++; txCount++; } });
    data.expenses.forEach(e => { const d = new Date(e.date); if (d >= startDate && d <= endDate) totalExpenses += (e.amount || 0); });
    data.stockPurchases.forEach(p => { const d = new Date(p.date); if (d >= startDate && d <= endDate) totalStockPurchases += (p.amount || 0); });
    data.customerTransactions.forEach(t => { const d = new Date(t.date); if (d >= startDate && d <= endDate) { if (t.type === 'payment') customerPayments += (t.amount || 0); else if (t.type === 'sale_debt' || t.type === 'manual_debt') newDebt += (t.amount || 0); } });
    const netProfit = knownProfit - totalExpenses; const outstandingDebt = data.customers.reduce((sum, c) => sum + (c.balance || 0), 0);
    return { totalSales, knownProfit, unknownCount, totalExpenses, netProfit, totalStockPurchases, customerPayments, newDebt, outstandingDebt, txCount };
}

export function renderReports(container) {
    const data = window.data; const formatCurrency = window.formatCurrency; const getStartOfDay = window.getStartOfDay; const getEndOfDay = window.getEndOfDay; const getStartOfMonth = window.getStartOfMonth; const getEndOfMonth = window.getEndOfMonth;
    let startDate, endDate;
    if (window.activeReportTab === 'daily') { startDate = getStartOfDay(new Date()); endDate = getEndOfDay(new Date()); } 
    else if (window.activeReportTab === 'monthly') { startDate = getStartOfMonth(window.currentReportMonth); endDate = getEndOfMonth(window.currentReportMonth); } 
    else { startDate = new Date(2000, 0, 1); endDate = new Date(); }
    const stats = calculateReportData(startDate, endDate); const monthName = window.currentReportMonth.toLocaleString('default', { month: 'long', year: 'numeric' });
    container.innerHTML = `<div class="tabs"><button class="tab-btn ${window.activeReportTab === 'daily' ? 'active' : ''}" onclick="setReportTab('daily')">Daily</button><button class="tab-btn ${window.activeReportTab === 'monthly' ? 'active' : ''}" onclick="setReportTab('monthly')">Monthly</button><button class="tab-btn ${window.activeReportTab === 'total' ? 'active' : ''}" onclick="setReportTab('total')">Total</button></div>${window.activeReportTab === 'monthly' ? `<div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;"><button class="btn btn-sm btn-secondary" onclick="changeReportMonth(-1)"><i class="fas fa-chevron-left"></i></button><h3 style="margin:0;">${monthName}</h3><button class="btn btn-sm btn-secondary" onclick="changeReportMonth(1)"><i class="fas fa-chevron-right"></i></button></div>` : ''}${window.activeReportTab === 'daily' ? `<button class="btn btn-secondary" style="margin-bottom:15px;" id="btn-reset-day" onclick="resetDailyReport()"><i class="fas fa-sync-alt"></i> Start New Business Day</button>` : ''}<div class="dashboard-grid"><div class="card profit"><h3>Total Sales</h3><div class="value">${formatCurrency(stats.totalSales)}</div></div><div class="card profit"><h3>Known Profit</h3><div class="value">${formatCurrency(stats.knownProfit)}</div></div><div class="card"><h3>Transactions</h3><div class="value">${stats.txCount}</div></div><div class="card"><h3>Unknown Profit Txns</h3><div class="value" style="color:var(--warning);">${stats.unknownCount}</div></div><div class="card debt"><h3>Expenses</h3><div class="value">${formatCurrency(stats.totalExpenses)}</div></div><div class="card profit"><h3>Net Profit</h3><div class="value">${formatCurrency(stats.netProfit)}</div></div><div class="card"><h3>Stock Purchases</h3><div class="value">${formatCurrency(stats.totalStockPurchases)}</div></div><div class="card"><h3>Customer Payments</h3><div class="value" style="color:var(--primary);">${formatCurrency(stats.customerPayments)}</div></div></div><div class="card debt"><h3>Outstanding Customer Debt</h3><div class="value">${formatCurrency(stats.outstandingDebt)}</div><p style="font-size:13px; color:var(--gray); margin-top:5px;">Total across all customers</p></div>`;
}
export function setReportTab(tab) { window.activeReportTab = tab; renderReports(document.getElementById('app-content')); }
export function changeReportMonth(direction) { window.currentReportMonth.setMonth(window.currentReportMonth.getMonth() + direction); renderReports(document.getElementById('app-content')); }
export async function resetDailyReport() { if (!confirm("Start new business day? Previous records remain in Monthly/Total reports.")) return; window.showLoading('btn-reset-day', "Resetting..."); try { await setDoc(doc(window.db, "settings", window.currentUserId), { businessDayStart: new Date().toISOString() }, { merge: true }); window.data.settings.businessDayStart = new Date().toISOString(); alert("New day started!"); renderReports(document.getElementById('app-content')); } catch (error) { alert("Failed."); } finally { window.hideLoading('btn-reset-day'); } }