import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration for the existing MyBusiness Firebase project.
///
/// The Web values come from the existing vanilla-JS Firebase configuration in
/// this project. Android/iOS native apps should use the platform config
/// generated by Firebase after registering the same package/bundle id.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQqnIhMCGd4_FRApjkns3HjIrqw2V1qFc',
    appId: '1:367002926256:web:0b5139dab24d901d9c8f75',
    messagingSenderId: '367002926256',
    projectId: 'mybusinessapp-4734c',
    authDomain: 'mybusinessapp-4734c.firebaseapp.com',
    storageBucket: 'mybusinessapp-4734c.firebasestorage.app',
  );

  // Android initialization intentionally comes from the native Firebase
  // configuration (google-services.json). Do not reuse the Web appId here.
  // Register com.mybusiness.pos in the existing Firebase project and replace
  // android/app/google-services.json with the file downloaded from Firebase Console.

  static const FirebaseOptions ios = web;
}
